version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mabmodel:latest
    container_name: mabmodel_app
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
